AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Scala Sample

Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorld/target/scala-2.13/HelloWorldFunction.jar
      Handler: handler.HelloWorldHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        HelloWorldEvent:
          Type: Api
          Properties:
            Path: /helloworld
            Method: get